### ISSUE TITLE
Recent commit to set execution requirements for XCode causes master to break

### ISSUE THREAD

**Issue by kitofans** [bazelbuild/rules_apple#687] opened 2020-01-01 22:58 UTC
https://github.com/bazelbuild/rules_apple/commit/83142df170d1ceff6d38a32f56663a5d5663cfde, and related commits across apple_support and rules_swift, breaks master for all rules, including tulsi.

The issue is that bazel 2.0 and below (i.e, all released bazel versions) do not include the `availability()` method on the XcodeVersionConfig struct. HEAD of bazel includes this, but this has not yet been released. The related commits in apple_support and rules_swift require this attribute (and the commit in this repo also includes a backwards-incompatible change).

In fact, because rules_apple does not pin the commits of the dependencies apple_support and rules_swift (they are just git_repositories at master), even if a consumer pins the rules_apple version, rules_apple's dependencies still pull in the offending code.

A workaround is for the consumer to explicitly pin versions of all three repositories to a commit before the offending one.

**Comment by steeve** [comment] 2020-01-02 11:16
Indeed, the real issue is that the dependencies are not pinned.
If nobody has done it I’ll try and do a PR, which will pin master for it to work with bazel 2.0.0.

But that’s part of the problem. All released versions are broken (since they pin on master), so I advise also reverting the commit in apple_support for now.

**Comment by thomasvl** [comment] 2020-01-02 13:46
You can pull in the dependencies in your own WORKSPACE file pinned to what ever version you desire.

**Comment by allevato** [comment] 2020-01-02 15:07
To elaborate, this is working as intended; the breakage is only if you are using the rules at HEAD but Bazel not at HEAD.

Due to resource constraints, as of #632, we only guarantee that rules_apple, rules_swift, and apple_support's master branches at HEAD are compatible with Bazel's master branch at HEAD—this is what our CI pipeline verifies. In _most_ cases that will line up with some Bazel release and historically that has been true, but occasionally a new feature will land that requires changes across all four repositories, and changes to the rules can get committed before the corresponding Bazel release is cut.

Therefore, we recommend that you pin apple_support, rules_swift, and rules_apple to specific commits that are compatible with the version of Bazel that you are using; if you depend on the repositories from master, you risk having a floating dependency that can change from underneath you at any time, and which may not be compatible with your current Bazel.

**Closed by allevato** 2020-01-02 15:07 UTC
