### ISSUE TITLE
rules_apple and docs are failing with Bazel@HEAD in CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_apple#2290] opened 2023-10-17 06:30 UTC
rules_apple (Last Green Bazel) : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#_

Logs:
```
ERROR: /Users/buildkite/builds/bk-imacpro-19/bazel-downstream-projects/rules_apple/test/starlark_tests/targets_under_test/apple/static_library/BUILD:26:21: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package '@[unknown repo 'build_bazel_apple_support' requested from @bazel_skylib~1.3.0]//platforms': The repository '@[unknown repo 'build_bazel_apple_support' requested from @bazel_skylib~1.3.0]' could not be resolved: No repository visible as '@build_bazel_apple_support' from repository '@bazel_skylib~1.3.0'
(04:11:45) ERROR: Analysis of target '//test/starlark_tests:apple_static_library_incoming_watchos_platform_mismatch_test' failed; build aborted: Analysis failed
(04:11:45) INFO: Elapsed time: 3.608s, Critical Path: 0.60s
(04:11:45) INFO: 10 processes: 2 internal, 8 darwin-sandbox.
(04:11:45) ERROR: Build did NOT complete successfully
(04:11:45) FAILED:
```
Steps:
```
git clone https://github.com/bazelbuild/rules_apple.git 
git reset d0180e6f48236f444a2a45c0c6485566f6a0b786 --hard
export USE_BAZEL_VERSION=2ddacab80af1dca3c04e74809827c47ec4bc8498
bazel build --config=visionos tools/... test/...

```

rules_apple (Doc tests ) : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3b61-d97f-4292-977b-828d1a337b2f
```
ERROR: Skipping 'doc/...': error loading package under directory 'doc': error loading package 'doc': Unable to find package for @[unknown repo 'io_bazel_stardoc' requested from @]//stardoc:stardoc.bzl: The repository '@[unknown repo 'io_bazel_stardoc' requested from @]' could not be resolved: No repository visible as '@io_bazel_stardoc' from main repository.
(02:15:56) ERROR: error loading package under directory 'doc': error loading package 'doc': Unable to find package for @[unknown repo 'io_bazel_stardoc' requested from @]//stardoc:stardoc.bzl: The repository '@[unknown repo 'io_bazel_stardoc' requested from @]' could not be resolved: No repository visible as '@io_bazel_stardoc' from main repository.
(02:15:56) INFO: Elapsed time: 0.540s
(02:15:56) INFO: 0 processes.
(02:15:56) ERROR: Build did NOT complete successfully
```
Steps:
```
git clone https://github.com/bazelbuild/rules_apple.git 
git reset d0180e6f48236f444a2a45c0c6485566f6a0b786 --hard
export USE_BAZEL_VERSION=2ddacab80af1dca3c04e74809827c47ec4bc8498
bazel  test doc/...
```

**Comment by brentleyjones** [comment] 2023-10-17 12:46
Looks like a bzlmod regression?

**Comment by brentleyjones** [comment] 2023-10-17 17:01
Should be fixed by https://github.com/bazelbuild/rules_apple/pull/2294.

**Comment by luispadron** [comment] 2023-10-19 21:10
Closing as fixed, let us know if you still run into issues

**Closed by luispadron** 2023-10-19 21:10 UTC
