### ISSUE TITLE
Breaks with Bazel @ HEAD

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/rules_apple#468] opened 2019-06-07 09:12 UTC
The rules_apple pipeline on Bazel CI breaks with Bazel at HEAD.

This might be a duplicate of https://github.com/bazelbuild/rules_apple/issues/456

CI log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1026#92a18b3a-822d-40be-97d5-d6e0d4bc7042

Source tree: https://github.com/bazelbuild/rules_apple/commit/6ea5e28ee58af390fdf3a1cdb005f691aaed85eb

Bazel version: built at https://github.com/bazelbuild/bazel/commit/12c7942f45185e15ac26c383644b5d63a3c25269

Build log:
```
ERROR: /Users/buildkite/builds/bk-imacpro-20/bazel-downstream-projects/rules_apple/test/starlark_tests/targets_under_test/ios/BUILD:211:1: Couldn't build file test/starlark_tests/targets_under_test/ios/sticker_ext.zip: Processing and signing sticker_ext failed (Exit 1): process-and-sign.sh failed: error executing command
  (cd /private/var/tmp/_bazel_buildkite/f5cf2bf0dfaeb14ee44949e2b4375747/execroot/build_bazel_rules_apple && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=12.2 \
    XCODE_VERSION_OVERRIDE=10.2.1.10E1001 \
  bazel-out/darwin-fastbuild-f2649e6c3a5ca95b009a37eacb1d2c8f/bin/test/starlark_tests/targets_under_test/ios/sticker_ext-intermediates/process-and-sign.sh)
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_buildkite/f5cf2bf0dfaeb14ee44949e2b4375747/execroot/build_bazel_rules_apple/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 162, in <module>
    sys.exit(main(sys.argv))
  File "/private/var/tmp/_bazel_buildkite/f5cf2bf0dfaeb14ee44949e2b4375747/execroot/build_bazel_rules_apple/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 156, in main
    filtered_stderr = _filter_codesign_output(stderr)
  File "/private/var/tmp/_bazel_buildkite/f5cf2bf0dfaeb14ee44949e2b4375747/execroot/build_bazel_rules_apple/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 116, in _filter_codesign_output
    for line in codesign_output.split("\n"):
TypeError: a bytes-like object is required, not 'str'
----------------
Note: The failure of target @build_bazel_rules_apple//tools/codesigningtool:codesigningtool (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.
 
If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------

```

**Comment by thomasvl** [comment] 2019-06-07 14:18
Duplicate of #456

**Closed by thomasvl** 2019-06-07 14:18 UTC

**Comment by thomasvl** [comment] 2019-06-07 14:22
This is one of those cases where it would be nice to better duplicate this sort config ourselves.  We have https://github.com/bazelbuild/rules_apple/blob/master/.bazelci/presubmit.yml#L17-L33, but that likely doesn't catch new flags you are adding for testing manually.  This lets us more directly target issues to keep things green while not also having to enable those flags on all our other configs.
