### ISSUE TITLE
Rules_apple red on buildkite

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_apple#233] opened 2018-10-02 10:33 UTC
Hello :)

Rules_apple are no longer green on buildkite (https://buildkite.com/bazel/rules-apple-darwin/builds/129#21532563-766d-4b1b-84ad-47a5f2553c2f), even though there is no rules_apple commit in last 20 days. I blame the upgraded mac workers are to blame?

cc @philwo 
cc @sergiocampama

**Comment by philwo** [comment] 2018-10-02 10:42
This is probably caused by the upgrade to macOS 10.14 and Xcode 10.0 and something that the rules_apple people would have to fix.

**Comment by sergiocampama** [comment] 2018-10-02 11:02
I'll look into this today

**Comment by sergiocampama** [comment] 2018-10-02 15:00
Could we be notified of such changes in the future? Breaking and pushing the fixes after the fact seems like the wrong approach for infrastructure changes.

**Comment by philwo** [comment] 2018-10-02 15:04
Unfortunately we don't have the capacity to slowly roll out changes like this or run multiple versions of macOS / Xcode in parallel. In general, our main CI machines will track the latest macOS and Xcode and update shortly after they become available (I usually update my personal machines the minute they come out and will do the CI machines the next business day).

I can offer to e-mail bazel-discuss@ (or bazel-dev@?) in the future with a notice period of a few days that I'm going to upgrade the machines if that helps, though?

**Comment by mhlopko** [comment] 2018-10-02 15:05
I think in this case the "fix" would be to force rerun all projects after worker upgrade? Wdyt Philipp?

**Comment by sergiocampama** [comment] 2018-10-02 15:08
Is there a way to configure emails when buildkite goes red? I wasn't even aware it had become broken.

**Comment by sergiocampama** [comment] 2018-10-04 13:15
this should be fixed now

**Closed by sergiocampama** 2018-10-04 13:15 UTC

**Comment by philwo** [comment] 2018-10-04 13:39
> Is there a way to configure emails when buildkite goes red? I wasn't even aware it had become broken.

I don't think so, but that sounds like a nice feature request. I filed one: https://github.com/bazelbuild/continuous-integration/issues/342
